baseURL = 'https://entrepreneur.42tokyo.jp/'
languageCode = "ja"
title = "42 起業部公式サイト"
theme = "42-theme"

[params]
  description = "42 起業部の公式サイトです。"
  author = "42 起業部"
  dateFormat = "2024-11-01"

[permalinks]
project = "/project/:sections/:slug/"

[security]
  [security.remote]
    ignoreCertErrors = ["42tokyo.jp"]
  [security.http]
    [security.http.mediaTypes]
      "image/jpeg" = true
      "image/png" = true
      "image/webp" = true

