baseURL = "https://entrepreneur.42tokyo.jp/"
languageCode = "ja"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

title = "42 Tokyo 起業部公式サイト"

[languages]
  [languages.ja]
    languageName = "日本語"
    params.lang = "ja"

  [languages.en]
    languageName = "English"
    params.lang = "en"

  [languages.fr]
    languageName = "Français"
    params.lang = "fr"

[params]
  description = "42 Tokyo 起業部の公式サイトです。"
  author = "42 Tokyo 起業部"
  dateFormat = "2006-01-02"

[permalinks]
  project = "/project/:sections/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^TRUSTSITE_ID$']

[sitemap]
  filename = "sitemap.xml"
  changefreq = "daily"
  priority = 0.5
