baseURL = 'https://home-page-b1m.pages.dev/'
languageCode = "ja"
title = "42 起業部公式サイト"
theme = "42-theme"

[params]
  description = "42 起業部の公式サイトです。"
  author = "42 起業部"
  dateFormat = "2024-11-01"

[permalinks]
project = "/project/:sections/:slug/"
