name: Update Hugo Content

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Hugo repository
        uses: actions/checkout@v3

      - name: List repositories with "project" in their name
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/orgs/42TokyoEntrepreneur/repos | \
            jq -r '.[] | select(.name | contains("project")) | .name' > repo_list.txt

      - name: Clone and copy Markdown files
        run: |
          while read repo; do
            echo "Processing repository: $repo"
            git clone https://github.com/42TokyoEntrepreneur/$repo /tmp/$repo
            mkdir -p content/project/$repo
            cp /tmp/$repo/public/*.md content/project/$repo/
          done < repo_list.txt

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Update project content"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
